server/guestpage/urls.py
from django.conf.urls import url
from . import views

app_name = 'guestpage'

urlpatterns = [
    url(r'^$', views.guest, name='guest'),
]

server/mainpage/urls.py
from django.conf.urls import include,url
from . import views

app_name = 'mainpage'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student/',include('student.urls')),
]

server/messmenu/urls.py
from django.conf.urls import url
from . import views

app_name= 'messmenu'

urlpatterns = [
    url(r'^$', views.messmenu, name='messmenu'),
]

server/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from server import views

urlpatterns = [
    url(r'^$',views.gohome, name='gohome'),
    url(r'^admin/', admin.site.urls),
    url(r'^mainpage/',include('mainpage.urls')),
    url(r'^guestpage/',include('guestpage.urls')),
    url(r'^messmenu/',include('messmenu.urls')),
    url(r'^adminpage/',include('adminpage.urls')),
    #url(r'^student/',include('student.urls')),
]

server/mainpage/models.py
from django.db import models

# Create your models here.

server/mainpage/views.py
from django.shortcuts import render, HttpResponse, redirect
from student.models import student_details
from student.forms import studentlogin


# Create your views here.
def index(request):
    if request.method == 'POST':
        form = studentlogin(request.POST)
        if form.is_valid():
            us = form.cleaned_data['us']
            pw = form.cleaned_data['pw']
            user = student_details.objects.all().filter(usn=us).filter(pwd=pw)
            if user:
                user = user.values()
                usid = user[0]['usn']
                return redirect('student/'+usid)
                #return redirect('student:details')
            else:
                return render(request, 'mainpage/index.html', {'form': form, 'message': ' Invalid login credentials'})
    form = studentlogin()
    return render(request, 'mainpage/index.html', {'form': form})

server/mainpage/templates/mainpage/index.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <title>Mess Management System</title>
    {% load static %}
    <link rel=stylesheet href='{% static "mainpage/style.css" %}'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class='topheader'><b>Mess Management System</b></div>
    {% if message %}
    <div class="alert alert-danger fade in" ><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><span class="glyphicon glyphicon-remove"></span><strong>{{ message }}</strong></div>
    {% endif %}

    <div class="container-fluid">
        <div class="col-sm-4">
            <div class='box'>
                <div class='subhead'><b>Mess Registration</b></div>
                {% load static %}
                <img src='{% static "mainpage/register.png" %}'>
                <button type="button" class="btn btn-primary" data-toggle='modal' data-target='#popup'>Login</button>
                
                <div class='modal fade' id='popup'>
                    <div class='modal-dialog'>
                        <div class='modal-content'>
                           
                            <div class='modal-header'>
                                <button type='button' id="btn" class='close' data-dismiss='modal'>&times;</button>
                                <h2 class='modal-title'>Log In</h2>
                            </div>

                            <div class='modal-body'>
                                <form role='form' method="post">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <!--<div class='form-group'>
                                        <input type='text' class='form-control' placeholder='Registration no.'>
                                    </div>
                                    <div class='form-group'>
                                        <input type='password' class='form-control' placeholder='Password'>
                                    </div>-->
                                    <button type='submit' class='btn btn-primary'>Click Here To Log In</button>
                                </form>
                            </div>
                            
                            <!--
                            <div class='modal-footer'>
                                <button class='btn btn-primary'>Click Here To Log In</button>
                            </div>
                            -->
                        </div>
                    </div>                    
                </div>
                
            </div>
        </div>
        
        <div class="col-sm-4">
            <div class='box'>
                <div class='subhead'><b>Mess Menu</b></div>
                {% load static %}
                <img src='{% static "mainpage/food3.png" %}'>
                <a href="{% url 'messmenu:messmenu' %}"><button type="button" class="btn btn-primary">See details</button></a>
            </div>
        </div>
        <div class="col-sm-4">
            <div class='box'>
                <div class='subhead'><b>Pre-book your meal</b></div>
                {% load static %}
                <img src='{% static "mainpage/book.png" %}'>
                <a href="{% url 'guestpage:guest' %}"><button type="button" class="btn btn-primary">Book Meal</button></a>
            </div>
        </div>
    </div>
    
    <div class='pagebottom'>
    DBMS PROJECT © V SEM 2017<br>
    </div>

</body>
    
</html>