server/adminpage/urls.py
from django.conf.urls import url
from . import views

app_name = 'adminpage'

urlpatterns = [
    url(r'^$', views.admin, name='admin'),
    url(r'^adminlogin/(?P<aid>[0-9]+)$', views.manageadmin, name='adminlogin'),
]

server/mainpage/urls.py
from django.conf.urls import include,url
from . import views

app_name = 'mainpage'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student/',include('student.urls')),
]

server/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from server import views

urlpatterns = [
    url(r'^$',views.gohome, name='gohome'),
    url(r'^admin/', admin.site.urls),
    url(r'^mainpage/',include('mainpage.urls')),
    url(r'^guestpage/',include('guestpage.urls')),
    url(r'^messmenu/',include('messmenu.urls')),
    url(r'^adminpage/',include('adminpage.urls')),
    #url(r'^student/',include('student.urls')),
]

server/adminpage/models.py
from django.db import models

# Create your models here.

class messadmin(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    pwd = models.CharField(max_length=15)
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50,null=True)
    messbno = models.PositiveIntegerField()
    email = models.EmailField()
    phone = models.CharField(max_length=15)

    def __str__(self):
        return self.fname + "-" + str(self.messbno)

server/adminpage/forms.py
from django import forms
from messmenu.models import menu

class adminlogin(forms.Form):
    aid = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Admin ID'}))
    pw = forms.CharField(label='',widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

DAYS = [
    ('zero','---Select Weekday---'),
    ('Monday','Monday'),
    ('Tuesday','Tuesday'),
    ('Wednesday','Wednesday'),
    ('Thursday','Thursday'),
    ('Friday','Friday'),
    ('Saturday','Saturday'),
    ('Sunday','Sunday'),
]

TYPE = [
    ('zero','---Select Meal Type---'),
    ('Breakfast','Breakfast'),
    ('Lunch','Lunch'),
    ('Dinner','Dinner'),
]



class enterdetails(forms.Form):
    days = forms.CharField(label='', widget=forms.Select(choices=DAYS, attrs={'class': 'messform'}))
    tp=forms.CharField(label='', widget=forms.Select(choices=TYPE, attrs={'placeholder':'Enter Meal Type','class':'field1'}))
    fd=forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Enter Meal Details','class':'field2'}))

    """class Meta:
        model=menu
        fields = ('tp','fd')
    """

server/adminpage/views.py
from django.shortcuts import render, redirect
from .models import messadmin
from messmenu.models import menu
from .forms import adminlogin, enterdetails


# Create your views here.
def admin(request):
    if request.method == 'POST':
        form = adminlogin(request.POST)
        if form.is_valid():
            aid = form.cleaned_data['aid']
            pw = form.cleaned_data['pw']
            user = messadmin.objects.all().filter(id=aid).filter(pwd=pw)
            if user:
                #us = messadmin.objects.get(id=aid)

                return redirect('adminlogin/'+aid)
            else:
                return render(request, 'adminpage/admin.html', {'form': form, 'message': ' Invalid Login Credentials'})
    form = adminlogin()
    return render(request, 'adminpage/admin.html', {'form': form})


def manageadmin(request,aid):
    f = enterdetails()
    us=messadmin.objects.get(pk=aid)

    if request.method == 'POST':

        form2 = enterdetails(request.POST)
        if form2.is_valid():
            d = form2.cleaned_data['days']
            typ = form2.cleaned_data['tp']
            m1 = form2.cleaned_data['fd']
            if d!='zero' and typ != 'zero':
                if typ == 'Breakfast':
                    var2 = 1
                elif typ == 'Lunch':
                    var2 = 2
                elif typ == "Dinner":
                    var2 = 3

                if d == 'Monday':
                    var1 = 1
                elif d== 'Tuesday':
                    var1 = 2
                elif d== 'Wednesday':
                    var1 = 3
                elif d== 'Thursday':
                    var1 = 4
                elif d== 'Friday':
                    var1 = 5
                elif d== 'Saturday':
                    var1 = 6
                elif d== 'Sunday':
                    var1 = 7
                administrator = messadmin.objects.get(pk=aid)
                menuvar = menu.objects.get(s1=var1,s2=var2,messbno=administrator.messbno)
                menuvar.weekday = d
                menuvar.type = typ
                menuvar.s2 = var2
                menuvar.food = m1
                menuvar.messbno = administrator.messbno
                menuvar.s1 = var1

                menuvar.save()

                return render(request,'adminpage/adminlogin.html',{'us': us, 'f': f,'message':'Menu has been updated'})
            else:
                return render(request, 'adminpage/adminlogin.html', {'us': us, 'f': form2})

    return render(request, 'adminpage/adminlogin.html',{'us':us,'f':f} )

server/adminpage/templates/adminpage/admin.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <title>Admin Login</title>
    {% load static %}
    <link rel=stylesheet href='{% static "adminpage/styleadmin.css" %}'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<div class='topheader'><a href="{% url 'mainpage:index' %}"><b>Mess Management System</b></a></div>
    {% if message %}
    <div class="alert alert-danger fade in" ><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><span class="glyphicon glyphicon-remove"></span><strong>{{ message }}</strong></div>
    {% endif %}
    <div class="container-fluid">
        <div class="col-sm-6">
            <div class='heading'>
                <b>Admin Login</b>
            </div>
        </div>
         
        <div class="col-sm-6">
            <form class='sideform' method="post">
               <!-- <input type='text' class='form-control' placeholder='Admin ID'>
                <input type='password' class='form-control' placeholder='Password'> -->
                {% csrf_token %}
                {{ form }}
                <button class='btn btn-primary'>Click Here To Log In</button>
            </form>
        </div>
    </div>
    <div class='pagebottom'>
    DBMS PROJECT © V SEM 2017<br>
    </div>

</body>
    
</html>

server/adminpage/templates/adminpage/adminlogin.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <title>Mess Management System</title>
    {% load static %}
    <link rel=stylesheet href='{% static "adminpage/styleadminlogin.css" %}'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'mainpage:index' %}">Mess Management System</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a>Home</a></li>
                <!--<li><a href="#">Feedback</a></li>-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'adminpage:admin' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        </div>
    </nav>

    <div class='container-fluid'>

        <div class='col-sm-3' id='sidebar'>
            <h2><strong>Welcome {{ us.fname }}!</strong></h2>
            <br><br><br>
            <h3><b>Profile Details</b></h3>
            <ul class='details'>
                <li>Full Name : {{ us.fname }} {{ us.lname }}</li>
                <li>Mess Block : {{ us.messbno }}</li>
                <li>Email : {{ us.email }}</li>
                <li>Phone : {{ us.phone }}</li>
            </ul>
        </div>
        <div class="col-sm-1"></div>

        <div class="col-sm-8">
            {% if message %}
                <div class="alert alert-success fade in" ><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><span class="glyphicon glyphicon-ok"></span><strong> {{ message }}</strong></div>
            {% endif %}
            <h1><b><div class="tex">Edit Mess Menu</div></b></h1><br>
            <form method="post">
                {% csrf_token %}
                {{ f.as_p }}
                <button type='submit' class="btn btn-primary" id="click">Submit</button>
            </form>
        </div>
    </div>
</body>
</html>